export type ThemeColors = (typeof THEMES)[keyof typeof THEMES];

export const THEMES = {
  abyss: {
    nodeBackgroundActive: '#00f0ff',
    nodeBackgroundInactive: 'transparent',
    nodeBackgroundInactiveDiamond: '#3a4b5c',
    nodeBackgroundUndiscovered: '#101419',
    nodeBackgroundSelectableDiamond: '#0f3c4c',
    nodeBorderInactive: '#4a6278',
    nodeBorderInactiveOption: 'transparent',
    nodeBorderSelectableOption: 'transparent',
    nodeBorderUndiscovered: 'transparent',
    nodeTextActive: '#000000',
    nodeTextInactive: '#b0c4de',
    nodeTextUndiscovered: 'transparent',
    optionTextNext: '#00f0ff',
    optionTextDefault: '#b0c4de',
    pathActive: '#008b99',
    pathInactive: '#3a4b5c',
    background: '#0a0d12',
    dots: '#2a3b4c',
  },
  default: {
    nodeBackgroundActive: "#ff4056",
    nodeBackgroundInactive: "transparent",
    nodeBackgroundInactiveDiamond: "#464646",
    nodeBackgroundUndiscovered: "#171717",
    nodeBackgroundSelectableDiamond: "#562e32",
    nodeBorderInactive: "#737373",
    nodeBorderInactiveOption: "transparent",
    nodeBorderSelectableOption: "transparent",
    nodeBorderUndiscovered: "transparent",
    nodeTextActive: "#ffffff",
    nodeTextInactive: "#d0d0d0",
    nodeTextUndiscovered: "transparent",

    optionTextNext: "#ff4056",
    optionTextDefault: "#c1c1c1",

    pathActive: "#a93543",
    pathInactive: "#5e5e5e",

    background: "#282828",
    dots: "#737373",
  },
  fallout: {
    nodeBackgroundActive: '#ffb300',
    nodeBackgroundInactive: 'transparent',
    nodeBackgroundInactiveDiamond: '#3a3528',
    nodeBackgroundUndiscovered: '#110f0a',
    nodeBackgroundSelectableDiamond: '#2a251a',
    nodeBorderInactive: '#59503a',
    nodeBorderInactiveOption: 'transparent',
    nodeBorderSelectableOption: 'transparent',
    nodeBorderUndiscovered: 'transparent',
    nodeTextActive: '#000000',
    nodeTextInactive: '#a3987e',
    nodeTextUndiscovered: 'transparent',
    optionTextNext: '#ffb300',
    optionTextDefault: '#a3987e',
    pathActive: '#cc9000',
    pathInactive: '#3a3528',
    background: '#0d0c08',
    dots: '#2d291e',
  },
  gore: {
    nodeBackgroundActive: '#990000',
    nodeBackgroundInactive: 'transparent',
    nodeBackgroundInactiveDiamond: '#2b0a0a',
    nodeBackgroundUndiscovered: '#0d0202',
    nodeBackgroundSelectableDiamond: '#1f0404',
    nodeBorderInactive: '#4d1111',
    nodeBorderInactiveOption: 'transparent',
    nodeBorderSelectableOption: 'transparent',
    nodeBorderUndiscovered: 'transparent',
    nodeTextActive: '#ffffff',
    nodeTextInactive: '#8c5959',
    nodeTextUndiscovered: 'transparent',
    optionTextNext: '#ff1a1a',
    optionTextDefault: '#b38080',
    pathActive: '#800000',
    pathInactive: '#2e0a0a',
    background: '#080101',
    dots: '#5f1313',
  },
  madness: {
    nodeBackgroundActive: '#bf00ff',
    nodeBackgroundInactive: 'transparent',
    nodeBackgroundInactiveDiamond: '#2a1b38',
    nodeBackgroundUndiscovered: '#0a0510',
    nodeBackgroundSelectableDiamond: '#1c1026',
    nodeBorderInactive: '#472d5c',
    nodeBorderInactiveOption: 'transparent',
    nodeBorderSelectableOption: 'transparent',
    nodeBorderUndiscovered: 'transparent',
    nodeTextActive: '#ffffff',
    nodeTextInactive: '#b299c4',
    nodeTextUndiscovered: 'transparent',
    optionTextNext: '#bf00ff',
    optionTextDefault: '#b299c4',
    pathActive: '#8c00bf',
    pathInactive: '#2a1b38',
    background: '#08040d',
    dots: '#4f2e66',
  },
  rust: {
    nodeBackgroundActive: '#d95c14',
    nodeBackgroundInactive: 'transparent',
    nodeBackgroundInactiveDiamond: '#3d2b24',
    nodeBackgroundUndiscovered: '#120e0c',
    nodeBackgroundSelectableDiamond: '#261a15',
    nodeBorderInactive: '#664539',
    nodeBorderInactiveOption: 'transparent',
    nodeBorderSelectableOption: 'transparent',
    nodeBorderUndiscovered: 'transparent',
    nodeTextActive: '#ffffff',
    nodeTextInactive: '#b59a8e',
    nodeTextUndiscovered: 'transparent',
    optionTextNext: '#d95c14',
    optionTextDefault: '#b59a8e',
    pathActive: '#a6440c',
    pathInactive: '#3d2b24',
    background: '#0d0a08',
    dots: '#2a1f1a',
  },
  toxic: {
    nodeBackgroundActive: '#39ff14',
    nodeBackgroundInactive: 'transparent',
    nodeBackgroundInactiveDiamond: '#405040',
    nodeBackgroundUndiscovered: '#121612',
    nodeBackgroundSelectableDiamond: '#1f401f',
    nodeBorderInactive: '#5c7a5c',
    nodeBorderInactiveOption: 'transparent',
    nodeBorderSelectableOption: 'transparent',
    nodeBorderUndiscovered: 'transparent',
    nodeTextActive: '#000000',
    nodeTextInactive: '#c2d6c2',
    nodeTextUndiscovered: 'transparent',
    optionTextNext: '#39ff14',
    optionTextDefault: '#c2d6c2',
    pathActive: '#22990c',
    pathInactive: '#405040',
    background: '#0c0f0c',
    dots: '#334c33',
  },
  void: {
    nodeBackgroundActive: '#e0e0e0',
    nodeBackgroundInactive: 'transparent',
    nodeBackgroundInactiveDiamond: '#2a2a2a',
    nodeBackgroundUndiscovered: '#0a0a0a',
    nodeBackgroundSelectableDiamond: '#1f1f1f',
    nodeBorderInactive: '#404040',
    nodeBorderInactiveOption: 'transparent',
    nodeBorderSelectableOption: 'transparent',
    nodeBorderUndiscovered: 'transparent',
    nodeTextActive: '#000000',
    nodeTextInactive: '#888888',
    nodeTextUndiscovered: 'transparent',
    optionTextNext: '#ffffff',
    optionTextDefault: '#666666',
    pathActive: '#999999',
    pathInactive: '#2a2a2a',
    background: '#050505',
    dots: '#222222',
  },
} as const;

export type ThemeName = keyof typeof THEMES;

export const TYPOGRAPHY = {
  nodeFontFamily: "var(--font-vesper), serif",
  nodeFontSize: "17.5px",
};
